name: mlenv
channels:
  - nvidia
  - conda-forge
  - pytorch-nightly
dependencies:
  - ipython
  - setuptools
  - pip
  - wheel
  - conda-content-trust
  - conda-libmamba-solver
  - scikit-learn
  - numpy
  - python
  - matplotlib
  - pandas
  - yaml
  - json
# The following are for using pytorch with a GPU
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=12.1
# These modules are computer vision specific
  - albumentations
  - imgaug
  - Pillow
  - segmentation-models-pytorch
  - pytorch-lightning==1.5.4
# Logging
  - tensorboardx
