name: mlenv
channels:
  - nvidia
  - conda-forge
  - pytorch-nightly
dependencies:
  - ipython
  - ipywidgets
  - tqdm
  - setuptools
  - wheel
  - numpy
  - matplotlib
  - pandas
  - yaml
# notebook environment
  - jupyterlab
  - notebook
  - nb_conda_kernels
# The following are for using pytorch with a GPU
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=12.1
# These modules are computer vision specific
  - opencv
  - albumentations
  - imaug
  - segmentation-models-pytorch
  - pytorch-lightning==1.5.4
# Logging
  - tensorboardx
