name: mlenv
channels:
  - nvidia
  - conda-forge
  - pytorch-nightly
dependencies:
  - ipython
  - setuptools
  - pip
  - wheel
  - conda-content-trust
  - conda-libmamba-solver
  - scikit-learn
  - numpy
  - python
  - matplotlib
  - pandas
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=12.1
